# Generated by Django 4.2.5 on 2023-09-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_listbook_identifier_alter_listbook_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbook',
            name='direct_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
